football/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    # url(r'^djangojs/', include('djangojs.urls')),
    url(r'^jsreverse/$', 'django_js_reverse.views.urls_js', name='js_reverse'),
    url(r'^index/', include('users.urls', namespace="index")),
    url(r'^teams/', include('teams.urls', namespace="teams")),
    url(r'^tour/', include('tournament.urls', namespace="tour")),
    url(r'^round/', include('round_in_game.urls', namespace="round")),
    url(r'^match/', include('match.urls', namespace="match")),
]

match/urls.py
from django.conf.urls import url
from match import views

urlpatterns = [
    url(r'^(?P<pk>[0-9]+)/$', views.ChooseRound.as_view(), name='match'),
    url(r'^(?P<pk>[0-9]+)/grid/$', views.grid, name='grid'),
    url(r'^(?P<pk>[0-9]+)/results/$', views.results, name='results'),
    url(r'^save_changes/(?P<pk>[0-9]+)/', views.save_changes, name="save_changes"),
]

rang/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    # url(r'^/', views.create_teams(), name='teams'),
]

match/models.py
from django.db import models
from teams.models import Team
from round_in_game.models import RoundInGame


class Match(models.Model):
    first_team = models.ForeignKey(Team,
                                   related_name='first_team')
    second_team = models.ForeignKey(Team,
                                    related_name='second_team')
    first_team_goals = models.SmallIntegerField(blank=True, null=True)
    second_team_goals = models.SmallIntegerField(blank=True, null=True)
    my_round = models.ForeignKey(RoundInGame)

round_in_game/models.py
from django.db import models
from tournament.models import Tournament


class RoundInGame(models.Model):
    TYPE_RANG = (
        (1, '1/8'),
        (2, '1/4'),
        (3, '1/2'),
        (5, 'final'),
        (4, 'third_place'),
        (6, 'regular'),
    )

    tournament = models.ForeignKey(Tournament)
    type_rang = models.SmallIntegerField(choices=TYPE_RANG)
    date_start = models.DateField()
    date_end = models.DateField()

match/views.py
import json
from django.core.serializers.json import DjangoJSONEncoder
from django.core.urlresolvers import reverse_lazy
from django.db.models import Sum, F
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.views.generic import ListView
from match.models import Match
from round_in_game.models import RoundInGame
from teams.models import Team
from tournament.models import Tournament


class ChooseRound(ListView):
    model = Match
    template_name = 'match/get_all_matchs.html'
    context_object_name = 'matchs'

    def get_context_data(self, **kwargs):
        context = super(ChooseRound, self).get_context_data(**kwargs)
        context[self.context_object_name] = Match.objects.filter(my_round_id=
        self.kwargs.get(
            'pk'))
        all_type_round = dict(RoundInGame.TYPE_RANG)
        cur_type = RoundInGame.objects.filter(
            id=self.kwargs.get('pk')).values_list('type_rang', flat=True)
        context['type_round'] = all_type_round.get(cur_type[0])
        tour_id = RoundInGame.objects.filter(
            id=int(self.kwargs.get('pk'))).values_list('tournament_id')
        tour = Tournament.objects.filter(id=tour_id).values_list('name',
                                                                 flat=True)
        context['tour'] = tour[0]
        context['round_id'] = self.kwargs.get('pk')
        return context


def save_changes(request, pk):
    if request.method == 'POST':
        options = dict()
        if request.POST['team'] == 'first':
            options['first_team_goals'] = int(request.POST['goals'])
        else:
            options['second_team_goals'] = int(request.POST['goals'])
        Match.objects.filter(id=pk).update(**options)
        return HttpResponse()
    else:
        return HttpResponse(status='400')


def grid(request, pk):
    tour_id = RoundInGame.objects.filter(id=pk).values_list('tournament_id',
                                                            flat=True)
    all_round = RoundInGame.objects.filter(tournament_id=tour_id[0]).exclude(
        type_rang=6).order_by('type_rang')
    return render(request, 'match/grid_template.html', context={
        'all_round': all_round})


def results(request, pk):
    if pk:
        my_query = '''select teams_team.id, teams_team.logo, teams_team.name, count(p.id) as count_games, sum(first_team_goals) as goals_scored, sum(second_team_goals) as goals_missed, first_team_id, sum(first_team_win) as first_victory,
                    sum(second_team_win) as first_defeat, sum(first_team_win)*3 as points,
                    case when sum(first_team_goals) > sum(second_team_goals) then sum(first_team_goals) - sum(second_team_goals)
                        else sum(second_team_goals) - sum(first_team_goals) end as difference
                    from (
                        select match_match.first_team_id, match_match.first_team_goals, match_match.id as id, match_match.second_team_goals,
                                case when match_match.first_team_goals > match_match.second_team_goals then 1 else 0 end as first_team_win,
                                case when match_match.second_team_goals > match_match.first_team_goals then 1 else 0 end as second_team_win
                        from match_match
                            join round_in_game_roundingame on match_match.my_round_id=round_in_game_roundingame.id
                            join tournament_tournament on round_in_game_roundingame.tournament_id=tournament_tournament.id
                        where round_in_game_roundingame.type_rang=%(round_type)s and tournament_tournament.id=%(tour_id)s
                        union all
                        select match_match.second_team_id as first_team_id, match_match.second_team_goals as first_team_goals, match_match.id as id,
                                match_match.first_team_goals as second_team_goals,
                                case when match_match.second_team_goals > match_match.first_team_goals then 1 else 0 end as first_team_win,
                                case when match_match.first_team_goals > match_match.second_team_goals then 1 else 0 end as second_team_win
                        from match_match
                            join round_in_game_roundingame on match_match.my_round_id=round_in_game_roundingame.id
                            join tournament_tournament on round_in_game_roundingame.tournament_id=tournament_tournament.id
                        where round_in_game_roundingame.type_rang=%(round_type)s and tournament_tournament.id=%(tour_id)s) as p
                        join teams_team on teams_team.id=p.first_team_id
                    group by first_team_id
                    order by points desc, goals_scored desc''' % dict(tour_id=pk, round_type=6)

        res_table = Match.objects.raw(my_query)
        print res_table[0]
        for r in res_table:
            print r
        return render(request, 'match/results_table.html', context={
            'res_table': res_table
        })
    else:
        return HttpResponseRedirect('/')

templates/match/get_all_matchs.html
{% extends 'base_template.html' %}
{% load static %}
{% block links %}
    <script src="{% static 'js/save_change_goals.js' %}"></script>
    <script src="{% static 'django_js_reverse/js/reverse.js' %}"></script>
    <script src="{% url 'js_reverse' %}" type="text/javascript"></script>
    <link rel="stylesheet" href="{% static 'css/style_match.css' %}" />
{% endblock %}
{% block body_app %}
    <div>
        {% csrf_token %}
        <label class="round">Round: {{ type_round }}</label>
        <label class="tour">In tour: {{ tour }}</label>
        <table class="table table-hover table-bordered">
            <thead>
                <tr>
                    <th colspan="2" class="text-center">First Team</th>
                    <th colspan="2" class="text-center">Second Team</th>
                </tr>
                <tr>
                    <th class="text-center">Team info</th>
                    <th class="text-center">Goals</th>
                    <th class="text-center">Goals</th>
                    <th class="text-center">Team info</th>
                </tr>
            </thead>
            <tbody>
                {% for match in matchs %}
                    <tr>
                        <td >
                            {% if match.first_team.logo == "" %}
                                <img src="{% static 'teams_logo/your-logo-here.png' %}" />
                            {% else %}
                                <img src="{{ match.first_team.logo }}" />
                            {% endif %}
                            {{ match.first_team.name }}
                        </td>
                        <td class="text-center">
                            {% if match.first_team_goals == None %}
                                {% if user.is_superuser %}
                                    <input class="goal form-control"
                                           data-match_id="{{ match.id }}"
                                           data-team="first"
                                           type="text" />
                                {% else %}
                                    <p>-</p>
                                {% endif %}
                            {% else %}
                                {{ match.first_team_goals }}
                            {% endif %}
                        </td>
                        <td class="text-center">
                             {% if match.second_team_goals == None%}
                                {% if user.is_superuser %}
                                    <input class="goal form-control"
                                           data-match_id="{{ match.id }}"
                                           data-team="second"
                                           type="text" />
                                {% else %}
                                    <p>-</p>
                                {% endif %}
                            {% else %}
                                {{ match.second_team_goals }}
                            {% endif %}
                        </td>
                        <td>
                            {% if match.second_team.logo == "" %}
                                <img src="{% static 'teams_logo/your-logo-here.png' %}" />
                            {% else %}
                                <img src="{{ match.second_team.logo }}" />
                            {% endif %}
                            {{ match.second_team.name }}
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        {% if type_round != 'regular' %}
            <div>
                <a href="{% url 'match:grid' round_id %}" class="btn btn-default">
                    Change Look
                </a>
            </div>
        {% endif %}
    </div>
{% endblock %}

templates/match/grid_template.html
{% extends 'base_template.html' %}
{% block links %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/grid_style.css' %}"/>
    <script src="{% static 'django_js_reverse/js/reverse.js' %}"></script>
    <script src="{% url 'js_reverse' %}" type="text/javascript"></script>
    <script src="{% static 'js/save_change_goals.js' %}" type="text/javascript"></script>
{% endblock %}
{% block body_app %}
    <div class="element">
        {% for round in all_round %}
            <div class="col-sm-3 col-xs-3">
                <label class="l">{{ round.get_type_rang_display }}</label>
                <div>
                    {% for match in round.match_set.all %}
                    <table class="table table-bordered">
                        <tbody>
                            <tr>
                                <td>
                                    {% if not match.first_team.logo %}
                                        <img src="{% static 'teams_logo/your-logo-here.png' %}" />
                                    {% else %}
                                        <img src="{{ match.first_team.logo }}" />
                                    {% endif %}
                                    {{ match.first_team.name }}
                                </td>
                                 <td>
                                {% if not match.second_team_goals %}
                                    {% if user.is_superuser %}
                                        <input class="goal"
                                           data-match_id="{{ match.id }}"
                                           data-team="first"
                                           type="text" />
                                    {% else %}
                                        <p>-</p>
                                    {% endif %}
                                {% else %}
                                    {{ match.first_team_goals }}
                                {% endif %}
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    {% if not match.first_team.logo %}
                                        <img src="{% static 'teams_logo/your-logo-here.png' %}" />
                                    {% else %}
                                        <img src="{{ match.second_team.logo }}" />
                                    {% endif %}
                                    {{ match.second_team.name }}
                                </td>
                                <td>
                                {% if not match.second_team_goals %}
                                    {% if user.is_superuser %}
                                        <input class="goal"
                                           data-match_id="{{ match.id }}"
                                           data-team="second"
                                           type="text" />
                                    {% else %}
                                        <p>-</p>
                                    {% endif %}
                                {% else %}
                                    {{ match.second_team_goals }}
                                {% endif %}
                                </td>
                            </tr>
                        </tbody>
                     </table>
                    {% endfor %}
                </div>
            </div>

        {% endfor %}
    </div>
{% endblock %}

templates/match/results_table.html
{% extends 'base_template.html' %}
{% block links %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/results.css' %}" />
{% endblock %}
{% block body_app %}
    <table class="table table-bordered">
        <thead>
            <tr>
                <th rowspan="2">Team name</th>
                <th rowspan="2">Played Games</th>
                <th rowspan="2">Victory</th>
                <th rowspan="2">Defeat</th>
                <th colspan="2">Goals</th>
                <th rowspan="2">Difference goals</th>
                <th rowspan="2">Points</th>
            </tr>
            <tr>
                <th>Scored</th>
                <th>Missed</th>
            </tr>
        </thead>
        <tbody>
            {% for raw in res_table %}
                <tr>
                    <td>
                        {% if raw.logo %}
                            <img src="/{{raw.logo}}" />
                        {% else %}
                            <img src="{% static 'teams_logo/your-logo-here.png' %}" />
                        {% endif %}
                        {{ raw.name }}
                    </td>
                    <td class="text-center">{{ raw.count_games }}</td>
                    <td class="text-center">{{ raw.first_victory }}</td>
                    <td class="text-center">{{ raw.first_defeat }}</td>
                    <td class="text-center">{{ raw.goals_scored }}</td>
                    <td class="text-center">{{ raw.goals_missed }}</td>
                    <td class="text-center">{{ raw.difference }}</td>
                    <td class="text-center">{{ raw.points }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}