football/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    # url(r'^djangojs/', include('djangojs.urls')),
    url(r'^jsreverse/$', 'django_js_reverse.views.urls_js', name='js_reverse'),
    url(r'^index/', include('users.urls', namespace="index")),
    url(r'^teams/', include('teams.urls', namespace="teams")),
    url(r'^tour/', include('tournament.urls', namespace="tour")),
    url(r'^round/', include('round_in_game.urls', namespace="round")),
    url(r'^match/', include('match.urls', namespace="match")),
]

rang/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    # url(r'^/', views.create_teams(), name='teams'),
]

round_in_game/urls.py
from django.conf.urls import url
from round_in_game import views

urlpatterns = [
    url(r'^$', views.ChooseTourView.as_view(), name='choose_tour'),
    url(r'^(?P<pk>[0-9]+)/$', views.get_all_in_tour, name='get_round_in_tour'),
    # url(r'^(?P<pk>[0-9]+)/teams/$', views.get_teams, name='get_teams'),
    url(r'^(?P<pk>[0-9]+)/teams/$', views.TeamList.as_view(), name='get_teams'),
    url(r'^(?P<pk>[0-9]+)/round/$', views.add_teams, name='add_teams'),
    url(r'^(?P<pk>[0-9]+)/gen_teams/$', views.gen_matchs, name='gen_matchs'),
    url(r'^create/$', views.create, name='create_round'),
    url(r'^(?P<pk>[0-9]+)/choose_type/$', views.choose_type, name='choose_type_round'),
]

templates/my_round/get_all_in_tour.html
{% extends 'base_template.html' %}
{% block links %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style_round.css' %}"/>
    <script src="{% static 'js/all_round_in_tour.js' %}"></script>
    <script src="{% static 'django_js_reverse/js/reverse.js' %}"></script>
    <script src="{% url 'js_reverse' %}" type="text/javascript"></script>
{% endblock %}
{% block body_app %}
{% csrf_token %}
    <div id="my_menu" class="col-sm-4 col-md-4">
        <ul id="tours" class="nav nav-pills nav-stacked">
            {% for tour in tours %}
            <li data-tour_id="{{ tour.id }}"
                data-tour_mode="{{ tour.mode }}"
                data-tour_dstart="{{tour.date_start}}"
                data-tour_dend="{{tour.date_end}}"
                data-url="{% url 'round:get_round_in_tour' tour.id %}">
                <div>
                    {{ tour.name }}
                </div>
                <div>
                    {{ tour.date_start }}
                    {{ tour.date_end }}
                </div>
            </li>
            {% endfor %}
        </ul>
    </div>
    <div id="content"  class="col-sm-8 col-md-8">
        <div class="dropdown">
            <label>Choose round</label>
            <select id="round_in_tour" class="form-control">
            </select>
        </div>
        <div>
            <label>Teams in choosed round</label>
            <ul id="teams_in_round" class="list-group"></ul>
        </div>
        <div>
            <a id="gen_matchs" class="btn btn-default">
                Generate matchs
            </a>
            <a id="look_image" href="" class="btn btn-default">
                Look image
            </a>
            <a id="add_new" href="" class="btn btn-default">
                Create New
            </a>
        </div>
    </div>

    <div id="modalAddTeam" class="modal fade" role="dialog">

        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">x</button>
                    <h4>Choose teams to add in this round</h4>
                </div>
                <div class="modal-body">
                    <ul id="all_teams" class="list-group"></ul>
                    <div id="countMatch">
                        <label class="inline">Choose count of match:</label>
                        <input type="number" id="count_match" class="form-control inline" min="1" max="5" />
                    </div>
                </div>
                <div class="modal-footer">
                    <a id="add_choosed" href="" class="btn btn-default">
                        Generate
                    </a>
                </div>
            </div>
        </div>
    </div>

    <div class="modal fade" id="errorModal" role="dialog">
        <div class="modal-dialog ">
            <div class="modal-content alert alert-danger">
                    <button type="button" class="close" data-dismiss="modal">
                        x
                    </button>
                    <h5>
                        <strong>ERROR!</strong>
                        You must to choose teams for generation
                    </h5>
            </div>
        </div>
    </div>

    <div id="modal_add_round" class="modal fade" role="dialog">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">x</button>
                    <h4>Choose type of new round</h4>
                </div>
                <div class="modal-body">
                    <div class="dropdown">
                        <select id="type_round" class="form-control">
                        </select>
                    </div>
                    <div class="date_end">
                        <label>Date start:</label>
                        <input class="form-control" id="date_start" name="date_start" type="text" />
                    </div>
                    <div class="date_start">
                        <label>Date end:</label>
                        <input  class="form-control" id="date_end" name="date_end" type="text" />
                    </div>
                    {% if user.is_superuser %}
                        <a id="create_round" href="" class="btn btn-default" >
                            Add new
                        </a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}