football/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    # url(r'^djangojs/', include('djangojs.urls')),
    url(r'^jsreverse/$', 'django_js_reverse.views.urls_js', name='js_reverse'),
    url(r'^index/', include('users.urls', namespace="index")),
    url(r'^teams/', include('teams.urls', namespace="teams")),
    url(r'^tour/', include('tournament.urls', namespace="tour")),
    url(r'^round/', include('round_in_game.urls', namespace="round")),
    url(r'^match/', include('match.urls', namespace="match")),
]

rang/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    # url(r'^/', views.create_teams(), name='teams'),
]

users/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views


urlpatterns = [
    url(r'^$', views.UsersView.as_view(), name='index'),
    url(r'^login', views.block_login_page, name='login'),
    url(r'^logout', views.logout, name='logout'),
    url(r'^loggedin', views.get_current_user, name='loggedin'),
    url(r'^registration', views.register_user, name='registration'),
    url(r'^vk_login', views.vk_login, name='vk_login'),
    url(r'^fb_login', views.fb_login, name='fb_login'),
    url(r'^my_profile', views.my_profile, name='my_profile'),
    url(r'^change_pass', views.change_pass, name='change_pass'),
    url(r'^(?P<pk>[0-9]+)/vote', views.vote, name='vote'),
    url(r'^res_vote', views.save_res_vote, name='res_vote'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import User


class Users(models.Model):
    user = models.OneToOneField(User)
    photo = models.ImageField(blank=True, upload_to="static/user_photo")

    def __str__(self):
        return self.user.username

users/forms.py
from PIL import Image
from django.forms import ImageField
from django.contrib.auth.models import User
from .models import Users
from django.contrib.auth.forms import UserCreationForm, PasswordChangeForm, \
    AuthenticationForm
from django.forms import ModelForm


class FormControlMixin(object):
    def __init__(self, *args, **kwargs):
        super(FormControlMixin, self).__init__(*args, **kwargs)
        for field in self.fields.itervalues():
            field.widget.attrs.update({'class': 'form-control'})


class MyPasswordChangeForm(FormControlMixin, PasswordChangeForm):
    pass


class AuthForm(FormControlMixin, AuthenticationForm):
    pass


class RegistrationForm(FormControlMixin, UserCreationForm):
    photo = ImageField(required=False)

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email', 'photo',
                  'password1', 'password2']

    def save(self, commit=True):
        user = super(RegistrationForm, self).save(commit=commit)
        new_user = Users(user=user)
        if self.cleaned_data['photo']:
            new_user.photo = self.cleaned_data['photo']
            image = Image.open(new_user.photo)
            size = (50, 50)
            image = image.resize(size, Image.ANTIALIAS)
            image.save(new_user.photo)
        if commit:
            new_user.save()
        return new_user


class ProfileForm(FormControlMixin, ModelForm):
    photo = ImageField(required=False)

    class Meta:
        model = User
        fields = ['photo', 'first_name', 'last_name']

    def save(self, commit=True):
        user = super(ProfileForm, self).save(commit=commit)
        update_user = Users.objects.get(user=user)
        if self.cleaned_data['photo']:
            update_user.photo = self.cleaned_data['photo']
            image = Image.open(update_user.photo)
            size = (50, 50)
            image = image.resize(size, Image.ANTIALIAS)
            image.save(update_user.photo)
        if commit:
            update_user.save()

        return update_user

users/views.py
import json
from tempfile import NamedTemporaryFile
import urllib
from django.contrib import auth
from django.core.files import File
from django.core.urlresolvers import reverse_lazy
from django.db.models import Avg, Max, Q
from django.shortcuts import render, redirect
from django.views import generic
from football.settings import VK_API_SECRET, VK_CLIENT_ID
from .models import Users
from django.http import HttpResponseRedirect, HttpResponse
from .forms import RegistrationForm, ProfileForm, MyPasswordChangeForm, AuthForm
import requests
from django.contrib.auth.models import User
from django.contrib.auth import login
from django.contrib.auth.views import login as django_login
from django.contrib.auth.decorators import login_required
from rang.models import Rang


def get_current_user(request):
    return render(request, 'users/loggedin.html')


def logout(request):
    response = auth.views.logout(request, next_page='/index/')
    response.delete_cookie('tour_id')
    return response


def vk_login(request):
    code = request.GET['code']
    url = 'https://oauth.vk.com/access_token'
    params = {
        'client_id': VK_CLIENT_ID,
        'client_secret': VK_API_SECRET,
        'redirect_uri': 'http://localhost:8000/index/vk_login',
        'code': code,
    }
    r = requests.get(url, params)
    d = json.loads(r.text)

    url1 = 'http://api.vkontakte.ru/method/users.get'
    params1 = {
        'uids': d['user_id'],
        'fields': 'photo_50',

    }
    r = requests.get(url1, params1)
    params = json.loads(r.text)
    params = params['response']
    file_name = '%s.jpeg' % d['email']

    user, created = User.objects.get_or_create(
        defaults={
            'first_name': params[0]['first_name'],
            'last_name': params[0]['last_name'],
            'username': d['email'],
        },
        email=d['email'])
    user.save()

    my_user, created = Users.objects.get_or_create(
        user=user)
    if created:
        f_tmp = NamedTemporaryFile()
        f_tmp.write(requests.get(params[0]['photo_50']).content)
        f_tmp.flush()
        my_user.photo.save(file_name, File(f_tmp))
        my_user.save()

    set_rang(my_user)

    user.backend = 'django.contrib.auth.backends.ModelBackend'
    user.save()
    login(request, user)
    return redirect('/index/loggedin/')


def fb_login(request):
    user_info = json.loads(request.POST.get("user", ""))
    file_name = '%s.jpeg' % user_info['email']

    user, created = User.objects.get_or_create(
        defaults={
            'first_name': user_info['first_name'],
            'last_name': user_info['last_name'],
            'username': user_info['email'],
        },
        email=user_info['email'])
    user.save()

    my_user, created = Users.objects.get_or_create(
        user=user)
    picture = user_info['picture'].get('data')

    if created:
        f_tmp = NamedTemporaryFile()
        f_tmp.write(requests.get(picture['url']).content)
        f_tmp.flush()
        my_user.photo.save(file_name, File(f_tmp))
        my_user.save()

    set_rang(my_user)

    user.backend = 'django.contrib.auth.backends.ModelBackend'
    user.save()
    login(request, user)
    return HttpResponse(reverse_lazy('index:loggedin'))


def set_rang(user):
    if Rang.objects.count() == 0:
        Rang.objects.create(rang=25, user=user)
    else:
        max_id = Rang.objects.values('user_id').annotate(Max('id'))
        id_arr = []
        for item in max_id:
            id_arr.append(item['id__max'])
        res = Rang.objects.filter(id__in=id_arr).aggregate(Avg('rang'))
        # rang_for_new_user = random.randint(0, my_round(res['rang__avg']))
        Rang.objects.create(rang=round(res['rang__avg']) * 0.7,
                            user=user)


def register_user(request):
    if request.POST:
        form = RegistrationForm(request.POST, request.FILES)
        if form.is_valid():
            my_new_user = form.save()
            set_rang(my_new_user)
            return HttpResponseRedirect(reverse_lazy('index:index'))
        else:
            return render(request, 'users/registration.html', context={
                'form': form
            })
    else:
        return render(request, 'users/registration.html', context={
            'form': RegistrationForm()
        })


def block_login_page(request):
    if request.user.is_authenticated():
        return HttpResponseRedirect('/index/')
    else:
        return django_login(request, 'users/login.html',
                            authentication_form=AuthForm)


@login_required(login_url='/index/login/')
def my_profile(request):
    if request.method == 'POST':
        my_form = ProfileForm(request.POST, request.FILES,
                              instance=request.user)

        if my_form.is_valid():
            my_form.save()
            return HttpResponseRedirect(reverse_lazy('index:index'))
        else:
            return render(request, 'users/my_profile.html', context={
                'form': my_form
            })
    else:
        must_to_vote = False
        my_user = request.user.users.first_user.all() | request.user.users.second_user.all()
        tours = None
        if request.COOKIES.get('tour_id'):
            already_voted = urllib.unquote(urllib.unquote(request.COOKIES.get('tour_id')))
            already_voted = json.loads(already_voted)
            if already_voted:
                tours = my_user.filter(tour__mode=4).exclude(tour__id__in=already_voted).values('tour', 'tour__name')
        else:
            tours = my_user.filter(tour__mode=4).values('tour', 'tour__name')

        cur_user_in = my_user.filter(tour__mode=4).exists()
        if cur_user_in and tours:
            must_to_vote = True
        return render(request, 'users/my_profile.html', context={
            'form': ProfileForm(instance=request.user),
            'change_pass': MyPasswordChangeForm(user=request.user),
            'must_to_vote': must_to_vote,
            'tours': tours
        })


def change_pass(request):
    if request.method == 'POST':
        change_pass_form = MyPasswordChangeForm(user=request.user,
                                                data=request.POST)

        if change_pass_form.is_valid():
            change_pass_form.save()
            return HttpResponseRedirect(reverse_lazy('index:my_profile'))
        else:
            return HttpResponse(json.dumps(change_pass_form.errors),
                                content_type='application/json')
    else:
        return HttpResponse(status='400')


class UsersView(generic.ListView):
    template_name = 'users/index.html'
    context_object_name = 'users_list'
    model = Users


def vote(request, pk):
    all_users = Users.objects.filter(Q(first_user__tour__id=pk) |
                                     Q(second_user__tour__id=pk)).exclude(
        user=request.user)
    return render(request, 'users/vote.html', context={
        'all_users': all_users,
        'tour_id': pk})


def save_res_vote(request):
    if request.method == 'POST':
        all_users = json.loads(request.POST['new_position'])
        tour_id = request.POST['tour_id']
        already_voted = []
        if tour_id not in already_voted:
            already_voted.append(tour_id)
        delta = 100 / len(all_users)

        new_points = {}
        max_point = 100
        for item in all_users:
            new_points[item] = max_point
            max_point -= delta

        last_ranges = Rang.objects.filter(tournament_id=tour_id)

        for item in last_ranges:
            if item.user_id in new_points:
                tmp_rang = (item.rang * item.count) + new_points[item.user_id]
                new_count = item.count + 1
                new_rang = tmp_rang / new_count
                Rang.objects.filter(user_id=item.user_id).update(
                                    rang=new_rang,
                                    count=new_count)
        return HttpResponse(reverse_lazy('index:my_profile'))
    else:
        return HttpResponse(status='400')

templates/users/index.html
{% extends 'base_template.html' %}
{% block body_app %}
    {% for user in users_list %}
        {% if user.photo %}
            <img src="/{{ user.photo }}"/>
        {% else %}
            {% load static %}
            <img src="{% static 'image/default.png' %}"/>
        {% endif %}
        {{ user.user.username }}
        {{ user.user.first_name }}
        {{ user.user.last_name }}
        {{ user.user.email }}
        <br/>
    {% endfor %}
{% endblock %}

templates/users/loggedin.html
{% extends 'base_template.html' %}
{% block body_app %}
    {% if user.is_authenticated %}
        <p>You are loggedin</p>
    {% endif %}
{% endblock %}

templates/users/login.html
{% extends 'base_template.html' %}
 {% block body_app %}
<script>
    (function(d, s, id) {
        var js, fjs = d.getElementsByTagName(s)[0];
        if (d.getElementById(id)) return;
        js = d.createElement(s); js.id = id;
        js.src = "//connect.facebook.net/en_US/sdk.js";
        fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));
</script>
    <div class="col-sm-4 col-sm-offset-4 col-md-4 col-md-offset-4">
        <form method="post" action="">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" class="btn btn-default" value="Login" />
        </form>
        <a href="/index/registration/" class="btn btn-default">
            Registration
        </a>
     <!-- VK registration -->
        {% load static %}
        <a href="https://oauth.vk.com/authorize?client_id=5098165&display=popup&redirect_uri=http://localhost:8000/index/vk_login&scope=photos,email&response_type=code&v=5.37">
            <img src="{% static 'image/vk_icon.png' %}" style="height: 30px; weidth: 30px;"  />
        </a>
        <a href="#" onclick="doLogin()">
            <script src="{% static 'js/fb_login.js' %}"></script>
            <img src="{% static 'image/fb_icon.jpeg' %}" style="height: 30px; weidth: 30px;" />
        </a>
    </div>
{% endblock %}

templates/users/my_profile.html
{% extends 'base_template.html' %}
{% block links %}
        {% load static %}
         <script src="{% static 'js/change_pass_errors.js' %}"></script>
         <script src="{% static 'django_js_reverse/js/reverse.js' %}"></script>
         <script src="{% url 'js_reverse' %}" type="text/javascript"></script>
         <script src="{% static 'js/js.cookie.js' %}" type="text/javascript"></script>
{% endblock %}
{% block body_app %}
    <div class="col-sm-4 col-sm-offset-3 col-md-4 col-md-offset-3">
        <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
            {% if user.users.photo %}
                <img src="/{{ user.users.photo }}" />
            {% else %}
                {% load static %}
                <img src="{% static 'image/default.png' %}"/>
            {% endif %}
            {% for field in form %}
                <label>{{ field.label }} :</label>
                {{ field }}
                <br/>
            {% endfor %}
            <a href="#myModal" role="button" class="btn btn-default"
                    data-toggle="modal">
                Change Password
            </a>
            <input type="submit" class="btn btn-default" value="Change" />
            {% if must_to_vote %}
                <a href="#choose_tour" data-already_voted="{{already_voted}}"
                   role="button" class="btn btn-default"
                        data-toggle="modal">
                    Vote
                </a>
            {% endif %}
        </form>
    </div>

<div class="modal fade" id="choose_tour" tabindex="-1" role="dialog"
     aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"
                        aria-hidden="true">x</button>
                <h4>You must to choose tour</h4>
            </div>
            <div class="modal-body">
                <div class="dropdown">
                    <select id="all_tours" class="form-control">
                        {% for tour in tours %}
                            <option data-tour_id="{{ tour.tour }}">
                                {{ tour.tour__name }}
                            </option>
                        {% endfor %}
                    </select>
                </div>
            </div>
            <div class="modal-footer">
                <a id="next_step" href="" class="btn btn-default">
                    Next Step
                </a>
            </div>
        </div>
    </div>
</div>


<div class="modal fade" id="myModal" tabindex="-1" role="dialog"
     aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"
                        aria-hidden="true">x</button>
                <h4>Change Password</h4>
            </div>

            <form id="my_form" method="post" action="{% url 'index:change_pass' %}">
                {% csrf_token %}
                <div class="modal-body">
                    {% for field in change_pass %}
                    <div class="form-group">
                            {{ field.label_tag }}
                            {{ field }}
                        <span class="help-block"></span>
                    </div>
                    {% endfor %}
                </div>
                <div class="modal-footer">
                    <button class="btn btn-default" data-dismiss="modal" aria-hidden="true">
                        Close
                    </button>
                    <input type="submit" class="btn btn-primary"
                           value="Save changes"/>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

templates/users/registration.html
{% extends 'base_template.html' %}
{% block links %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/registration.css' %}" />
{% endblock %}
{% block body_app %}
    <div class="col-sm-6 col-sm-offset-3 col-md-4 col-md-offset-3">
        <form id="my_form" method="post" enctype="multipart/form-data"
                action="{% url 'index:registration' %}">
            {% csrf_token %}
            {% for item in form %}
                <div class="form-group
                        {% if item.errors %} has-error {% endif %} ">
                        <strong>{{ item.label }} :</strong>

                        <p>
                            {{ item }}

                            <span class="help-block">
                                {% if item.errors %}
                                    {% for error in item.errors %}
                                           {{ error }}
                                    {% endfor %}
                                {% else %}
                                    {{ item.help_text }}
                                {% endif %}
                            </span>
                        </p>
                </div>
            {% endfor %}
            <div>
                 <input type="submit" class="btn btn-default" value="Registrate" />
            </div>
        </form>
    </div>
{% endblock %}

templates/users/vk_tmpl.html
{% extends 'base_template.html' %}
{% block body_app %}
    <p>Hello!</p>
{% endblock %}

templates/users/vote.html
{% extends 'base_template.html' %}
{% block links %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style_vote.css' %}" />
    <script src="{% static 'js/vote.js' %}"></script>
    <script src="https://johnny.github.io/jquery-sortable/js/jquery-sortable.js"></script>
    <script src="{% static 'django_js_reverse/js/reverse.js' %}"></script>
    <script src="{% url 'js_reverse' %}" type="text/javascript"></script>
    <script src="{% static 'js/js.cookie.js' %}" type="text/javascript"></script>
{% endblock %}
{% block body_app %}
    <div class="my_body">
        <ul class="list-group col-xs-8 col-xs-offset-2 col-sm-6 col-sm-offset-3 col-md-4 col-md-offset-3 simple_with_animation vertical"
                        data-tour_id="{{tour_id}}">
            {% for user in all_users %}
                <li class="list-group-item"
                        data-user_id="{{user.id}}">
                    {% if user.photo %}
                        <img src="/{{ user.photo }}" />
                    {% else %}
                        <img src="{% static 'image/default.png' %}" />
                    {% endif %}
                    {{user.user.username}}
                </li>
            {% endfor %}
        </ul>
        <a id="save_changes" href="" class="btn btn-default">
            Done
        </a>
        {% csrf_token %}
    </div>
{% endblock %}